# Generated by Django 4.2.9 on 2024-02-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0002_remove_eventmodel_club_remove_modelpost_club'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clubs',
            field=models.ManyToManyField(blank=True, null=True, related_name='members_clubs', to='app_clubs.club'),
        ),
    ]
