# Generated by Django 4.2.9 on 2024-03-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_clubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clubs',
        ),
    ]
