# Generated by Django 4.2.9 on 2024-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0006_club_users'),
        ('users', '0003_remove_user_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clubs',
            field=models.ManyToManyField(related_name='members_clubs', to='app_clubs.club'),
        ),
    ]
