# Generated by Django 4.2.9 on 2024-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/users/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
