# Generated by Django 4.2.9 on 2024-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(max_length=64, null=True, verbose_name='ФИО'),
        ),
    ]
