# Generated by Django 4.2.9 on 2024-03-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя пользователя в телеграм'),
        ),
    ]
