# Generated by Django 4.2.9 on 2024-03-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_tg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание о себе'),
        ),
    ]
