# Generated by Django 4.2.9 on 2024-03-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='uploads/users/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
