# Generated by Django 4.2.9 on 2024-04-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='uploads/users/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
