# Generated by Django 4.2.9 on 2024-04-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/users/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя пользователя в телеграм'),
        ),
    ]
