# Generated by Django 4.2.9 on 2024-02-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='club',
        ),
        migrations.RemoveField(
            model_name='modelpost',
            name='club',
        ),
    ]
