# Generated by Django 4.2.9 on 2024-01-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0002_alter_club_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
    ]
