# Generated by Django 4.2.9 on 2024-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0002_club_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelpost',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
    ]
