# Generated by Django 4.2.9 on 2024-02-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0002_remove_eventmodel_club_remove_modelpost_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_clubs.club'),
        ),
        migrations.AddField(
            model_name='modelpost',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_clubs.club'),
        ),
    ]
