# Generated by Django 4.2.9 on 2024-01-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0005_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ModelPost',
        ),
    ]
