# Generated by Django 4.2.9 on 2024-03-02 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_clubs', '0005_club_not_approved_alter_club_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='users',
            field=models.ManyToManyField(related_name='allusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
