# Generated by Django 4.2.9 on 2024-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0006_rename_post_modelpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(choices=[('Онлайн', 'Онлайн'), ('Офлайн', 'Офлайн')], max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
    ]
