# Generated by Django 4.2.9 on 2024-03-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0006_club_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='users',
        ),
    ]
