# Generated by Django 4.2.9 on 2024-03-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0007_remove_club_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='file_image',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
