# Generated by Django 4.2.9 on 2024-02-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0007_eventmodel_alter_modelpost_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpost',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_clubs.club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о клубе'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='format',
            field=models.CharField(choices=[('Онлайн', 'Онлайн'), ('Офлайн', 'Офлайн')], max_length=16, verbose_name='Формат проведения'),
        ),
    ]
