# Generated by Django 4.2.9 on 2024-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0008_club_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='file_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
