# Generated by Django 4.2.9 on 2024-02-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0009_alter_club_options_alter_eventmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_clubs.club'),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_clubs.club'),
        ),
    ]
