# Generated by Django 4.2.9 on 2024-03-08 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_clubs', '0011_alter_club_moderate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='not_approved',
            field=models.ManyToManyField(blank=True, null=True, related_name='notapproved', to=settings.AUTH_USER_MODEL),
        ),
    ]
