# Generated by Django 4.2.9 on 2024-03-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0016_alter_eventmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/posts/', verbose_name='Изображение'),
        ),
    ]
