# Generated by Django 4.2.9 on 2024-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0017_alter_modelpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
