# Generated by Django 4.2.9 on 2024-03-24 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0024_alter_modelpost_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
