# Generated by Django 4.2.9 on 2024-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0025_alter_modelpost_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpost',
            options={'ordering': ['-datetime'], 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='modelpost',
            name='type_content',
            field=models.CharField(blank=True, choices=[('news', 'Новости'), ('article', 'Статьи')], max_length=32, null=True, verbose_name='Тип поста'),
        ),
    ]
