# Generated by Django 4.2.9 on 2024-03-28 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_clubs', '0027_modelpost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifs',
            options={'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='notifs',
            name='receiver',
            field=models.ManyToManyField(null=True, related_name='notifs_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifs',
            name='sender',
            field=models.ManyToManyField(null=True, related_name='notifs_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
