# Generated by Django 4.2.9 on 2024-03-28 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_clubs', '0028_alter_notifs_options_notifs_receiver_notifs_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifs',
            name='receiver',
            field=models.ManyToManyField(null=True, related_name='notifs_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='notifs',
            name='sender',
            field=models.ManyToManyField(null=True, related_name='notifs_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='notifs',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notifs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время'),
        ),
    ]
