# Generated by Django 4.2.9 on 2024-03-28 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_clubs', '0029_alter_notifs_receiver_alter_notifs_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifs',
            name='sender',
        ),
        migrations.AddField(
            model_name='notifs',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
