# Generated by Django 4.2.9 on 2024-03-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0030_remove_notifs_sender_notifs_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifs',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_clubs.club'),
        ),
    ]
