# Generated by Django 4.2.9 on 2024-03-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0031_notifs_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Доп.информация о клубе'),
        ),
    ]
