# Generated by Django 4.2.9 on 2024-03-30 09:05

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0032_club_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
