# Generated by Django 4.2.9 on 2024-03-30 09:58

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0033_alter_modelpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='short_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Доп.информация о клубе'),
        ),
    ]
