# Generated by Django 4.2.9 on 2024-03-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0034_alter_club_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
