# Generated by Django 4.2.9 on 2024-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clubs', '0036_remove_eventmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='age',
            field=models.CharField(blank=True, choices=[('with_out', 'Без ограничений'), ('age1', '12+'), ('age1', '16+'), ('age1', '18+')], max_length=32, null=True, verbose_name='Тип поста'),
        ),
    ]
